version: '3'
services:
  varnish:
    image: varnish:6.0
    ports:
      - "80:80"
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
    depends_on:
      - nginx
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
